### PR TITLE
Updated backend URLs and headers for AQT API calls

### PR DESCRIPTION
**Pull request by ma5x**

### CODE REVIEW

**Comment by mtreinish** [comment]
@ma5x this looks good to me (deferring to you for the correctness of the endpoint url) but looking at the actual git metadata for the commits the CLA bot is getting confused because the email address in the git commits is set to `Max`. The bot is looking for an email address associated with your github account but it won't be able to (since `Max` isn't a valid email address. You'll probably have to use `git rebase -i` and amend the author string for the commits and then force push the updated branch to github to correct this.

**Comment by ma5x** [comment]
> @ma5x this looks good to me (deferring to you for the correctness of the endpoint url) but looking at the actual git metadata for the commits the CLA bot is getting confused because the email address in the git commits is set to `Max`. The bot is looking for an email address associated with your github account but it won't be able to (since `Max` isn't a valid email address. You'll probably have to use `git rebase -i` and amend the author string for the commits and then force push the updated branch to github to correct this.

Yeah, sorry for the misconfigured metadata on my side (already fixed it for future commits). As you already pushed the corrected URLs and headers to master, I think it's not necessary to for me to rebase and force-push this time.
Thanks for handling this!

**Comment by mtreinish** [comment]
@ma5x I apologize I made a typo in my git command trying to update the authorship tags for you and ended up pushing an old version of master to your fork instead of the updated version of this PR's commits (github automatically closed this when I pushed an old branch to your fork). I opened up #9 which takes your branch and commits just with the updated author metadata. If that looks good to you we can just merge that PR instead (the code is the same I only updated the author metadata).

**Comment by ma5x** [comment]
Sure, I'm perfectly fine with that. Sorry again for causing so much trouble for such a small change!

**Pull request closed without merging**
